# Generated by Django 5.2.8 on 2025-11-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Just Code Works', max_length=200)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('is_live', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Main Website Settings',
                'verbose_name_plural': 'Main Website Settings',
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main homepage slider', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Main Slider',
                'verbose_name_plural': 'Main Sliders',
            },
        ),
        migrations.CreateModel(
            name='MainSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('button_label', models.CharField(blank=True, max_length=100)),
                ('button_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='main_site.mainslider')),
            ],
            options={
                'verbose_name': 'Main Slide',
                'verbose_name_plural': 'Main Slides',
                'ordering': ['order'],
            },
        ),
    ]
