# Generated by Django 5.2.8 on 2025-11-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Slug used in the path, e.g. 'home', 'services', 'websites'.", max_length=120)),
                ('path', models.CharField(help_text="Full path used in the frontend, e.g. '/services', '/websites/one-page'.", max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', help_text="Content locale for this page, e.g. 'en', 'pt'.", max_length=5)),
                ('meta_title', models.CharField(blank=True, help_text='Optional SEO title. Defaults to page title if empty.', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Optional SEO description shown in search results.')),
                ('meta_slug', models.SlugField(blank=True, help_text='Optional URL slug override for this locale. Defaults to slug/path.', max_length=255)),
                ('indexable', models.BooleanField(default=True, help_text='If false, this page should be marked as noindex for search engines.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Main Website Page',
                'verbose_name_plural': 'Main Website Pages',
                'ordering': ['order', 'id'],
                'unique_together': {('slug', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='MainNavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', help_text='Language/locale for this navigation item', max_length=5)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], help_text='Where this item appears (header vs footer).', max_length=16)),
                ('column', models.PositiveSmallIntegerField(blank=True, help_text='For footer items: which column (1–5).', null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text='Explicit URL path or external link. Used if no Page is linked.', max_length=255)),
                ('is_external', models.BooleanField(default=False, help_text='If true, treat URL as external.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent item for dropdowns or nested links.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main_site.mainnavigationitem')),
                ('page', models.ForeignKey(blank=True, help_text='Optional link to a MainPage. If set, this overrides url.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items', to='main_site.mainpage')),
            ],
            options={
                'verbose_name': 'Main Website Navigation Item',
                'verbose_name_plural': 'Main Website Navigation Items',
                'ordering': ['location', 'locale', 'column', 'order', 'id'],
            },
        ),
    ]
