# Generated by Django 5.2.8 on 2025-11-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_mainpage_mainnavigationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="Technical section id, e.g. 'jcw-main-hero01'.", max_length=80)),
                ('internal_name', models.CharField(blank=True, help_text='Friendly name for the section, shown in editors.', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main_site.mainpage')),
            ],
            options={
                'verbose_name': 'Main Website Section',
                'verbose_name_plural': 'Main Website Sections',
                'ordering': ['order', 'id'],
                'unique_together': {('page', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='MainField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Field key used in the frontend config, e.g. 'title', 'subtitle'.", max_length=80)),
                ('label', models.CharField(blank=True, help_text='Human label shown in the editor UI.', max_length=120)),
                ('value', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main_site.mainsection')),
            ],
            options={
                'verbose_name': 'Main Website Field',
                'verbose_name_plural': 'Main Website Fields',
                'ordering': ['order', 'id'],
                'unique_together': {('section', 'key')},
            },
        ),
    ]
