# Generated by Django 5.2.8 on 2025-11-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_mainsection_mainfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainsection',
            options={'ordering': ['locale', 'order', 'id'], 'verbose_name': 'Main Website Section', 'verbose_name_plural': 'Main Website Sections'},
        ),
        migrations.AlterUniqueTogether(
            name='mainsection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mainsection',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português'), ('nl', 'Nederlands')], default='en', help_text='Language/locale for this section content', max_length=5),
        ),
        migrations.AlterField(
            model_name='mainnavigationitem',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português'), ('nl', 'Nederlands')], default='en', help_text='Language/locale for this navigation item', max_length=5),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português'), ('nl', 'Nederlands')], default='en', help_text="Content locale for this page, e.g. 'en', 'pt'.", max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='mainsection',
            unique_together={('page', 'identifier', 'locale')},
        ),
    ]
