# Generated by Django 5.0.8 on 2024-11-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_alter_mainsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
    ]