# Generated by Django 5.2.8 on 2025-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_mainpage_created_at_mainpage_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslide',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Main Slide', 'verbose_name_plural': 'Main Slides'},
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'ordering': ['-created_at'], 'verbose_name': 'Main Slider', 'verbose_name_plural': 'Main Sliders'},
        ),
        migrations.RemoveField(
            model_name='mainslide',
            name='button_label',
        ),
        migrations.RemoveField(
            model_name='mainslide',
            name='button_url',
        ),
        migrations.AddField(
            model_name='mainslide',
            name='animation_type',
            field=models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('none', 'No Animation')], default='fade', max_length=20),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='content',
            field=models.TextField(blank=True, help_text='Main slide content/description', null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='primary_cta_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='primary_cta_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='secondary_cta_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='secondary_cta_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='slide_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='slide_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Text color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='auto_play',
            field=models.BooleanField(default=True, help_text='Auto-advance slides'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='auto_play_interval',
            field=models.PositiveIntegerField(default=5000, help_text='Interval in milliseconds'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='background_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='background_overlay_opacity',
            field=models.FloatField(default=0.3, help_text='Overlay opacity over image/video'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='background_type',
            field=models.CharField(choices=[('gradient', 'Gradient'), ('image', 'Background Image'), ('video', 'Background Video')], default='gradient', max_length=20),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='background_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='gradient_direction',
            field=models.CharField(choices=[('to-r', 'To Right'), ('to-l', 'To Left'), ('to-b', 'To Bottom'), ('to-t', 'To Top'), ('to-br', 'To Bottom Right'), ('to-bl', 'To Bottom Left'), ('to-tr', 'To Top Right'), ('to-tl', 'To Top Left')], default='to-br', max_length=10),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='gradient_from',
            field=models.CharField(default='#1e40af', help_text='Gradient start color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='gradient_to',
            field=models.CharField(default='#3b82f6', help_text='Gradient end color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='particles_color',
            field=models.CharField(default='#ffffff', help_text='Primary particle color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='particles_colors',
            field=models.TextField(blank=True, help_text='JSON array of additional particle colors'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='particles_density',
            field=models.PositiveIntegerField(default=100, help_text='Number of particles (50-300)'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='particles_enabled',
            field=models.BooleanField(default=True, help_text='Enable particle effects'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='particles_multi_color',
            field=models.BooleanField(default=False, help_text='Use multiple particle colors'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='particles_opacity',
            field=models.FloatField(default=0.6, help_text='Particle opacity (0.1-1.0)'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='particles_size_max',
            field=models.PositiveIntegerField(default=3, help_text='Maximum particle size'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='particles_size_min',
            field=models.PositiveIntegerField(default=1, help_text='Minimum particle size'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='particles_speed',
            field=models.FloatField(default=1.0, help_text='Particle movement speed (0.5-3.0)'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='show_navigation',
            field=models.BooleanField(default=True, help_text='Show navigation arrows'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='show_pagination',
            field=models.BooleanField(default=True, help_text='Show pagination dots'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainnavigationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainnavigationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainslide',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainslide',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
