# Generated by Django 5.2.8 on 2025-11-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text="Internal key used to identify this dashboard template (e.g. 'default-tenant-dashboard').", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Human-readable name (e.g. 'Default tenant dashboard').", max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_for_tenants', models.BooleanField(default=False, help_text='If true, this template is used as the default for tenant dashboards.')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DashboardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text="Internal key for this block (e.g. 'live-preview', 'next-steps', 'stats').", max_length=100)),
                ('title', models.CharField(help_text='Title shown in the dashboard UI.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional description or helper text.')),
                ('region', models.CharField(default='main', help_text="Logical region in the dashboard layout (e.g. 'main', 'sidebar').", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Blocks with lower order appear first within their region.')),
                ('is_active', models.BooleanField(default=True)),
                ('target_route', models.CharField(blank=True, help_text="Optional route to navigate to when interacting with this block (e.g. '/dashboard/website').", max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tenant_dashboards.dashboardtemplate')),
            ],
            options={
                'ordering': ['region', 'order', 'id'],
            },
        ),
    ]
