# Generated by Django 5.2.8 on 2025-11-10 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="Slug used in the path, e.g. 'home', 'services', 'websites'.", max_length=120)),
                ('path', models.CharField(help_text="Full path used in the frontend, e.g. '/services', '/websites/one-page'.", max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('business_type', models.CharField(blank=True, max_length=150)),
                ('primary_goal', models.CharField(blank=True, choices=[('get-leads', 'Get leads / requests'), ('show-info', 'Show info / menu'), ('sell-online', 'Sell online'), ('take-bookings', 'Take bookings'), ('other', 'Other')], max_length=32)),
                ('primary_locale', models.CharField(default='en', help_text='Primary locale code, e.g. en, pt-pt, nl.', max_length=20)),
                ('additional_locales', models.JSONField(blank=True, default=list, help_text='Additional locale codes for this project.')),
                ('primary_color', models.CharField(blank=True, help_text='Simple colour name or CSS colour value.', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('one-page', 'One page'), ('multi-page', 'Multi page'), ('store', 'Online store'), ('booking', 'Booking'), ('portfolio', 'Portfolio'), ('custom', 'Custom')], default='one-page', max_length=20)),
                ('complexity', models.CharField(choices=[('starter', 'Starter'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='starter', max_length=20)),
                ('short_description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('recommended_for', models.TextField(blank=True)),
                ('sections_summary', models.JSONField(blank=True, default=list, help_text='List of section descriptions as shown in Templates Lab.')),
                ('estimated_pages', models.PositiveIntegerField(default=1)),
                ('has_store', models.BooleanField(default=False)),
                ('has_blog', models.BooleanField(default=False)),
                ('has_booking', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(help_text="Technical section id, e.g. 'jcw-main-hero01'.", max_length=80)),
                ('internal_name', models.CharField(blank=True, help_text='Friendly name for the section, shown in editors.', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sites.page')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('page', 'identifier')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sites.siteproject'),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='sites.template'),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="Field key used in the frontend config, e.g. 'title', 'subtitle'.", max_length=80)),
                ('label', models.CharField(blank=True, help_text='Human label shown in the editor UI.', max_length=120)),
                ('value', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sites.section')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('section', 'key')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('project', 'slug')},
        ),
    ]
