# Generated by Django 5.0.14 on 2025-11-10 16:15

import django.db.models.deletion
import sites.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_path', models.CharField(blank=True, help_text="Path where the bug happened, e.g. '/websites/one-page'.", max_length=255)),
                ('page_slug', models.CharField(blank=True, help_text="Optional slug of the page, e.g. 'websites-one-page'.", max_length=120)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('summary', models.CharField(help_text='Short summary of what went wrong.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='User description or steps to reproduce.')),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('locale', models.CharField(blank=True, max_length=32)),
                ('extra_meta', models.JSONField(blank=True, default=dict, help_text='Any extra JSON metadata (e.g. viewport size, browser info).')),
                ('project', models.ForeignKey(blank=True, help_text='Optional: project this bug relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to='sites.siteproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=sites.models.bug_screenshot_upload_to)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='sites.bugreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
