# Generated by Django 5.0.14 on 2025-11-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_bugreport_bugscreenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], help_text='Where this item appears (header vs footer).', max_length=16)),
                ('column', models.PositiveSmallIntegerField(blank=True, help_text='For footer items: which column (1–5).', null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text='Explicit URL path or external link. Used if no Page is linked.', max_length=255)),
                ('is_external', models.BooleanField(default=False, help_text='If true, treat URL as external.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, help_text='Optional link to a Page. If set, this overrides url.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items', to='sites.page')),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent item for dropdowns or nested links.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sites.navigationitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='sites.siteproject')),
            ],
            options={
                'ordering': ['location', 'column', 'order', 'id'],
            },
        ),
    ]
