# Generated by Django 5.2.8 on 2025-11-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_navigationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='accent_color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='allow_theme_toggle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='default_theme',
            field=models.CharField(default='dark', max_length=16),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='hero_particles_density',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='hero_particles_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='hero_particles_size',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='hero_particles_speed',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='primary_color',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
