# Generated by Django 5.2.8 on 2025-11-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_siteproject_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='page',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', help_text="Content locale for this page, e.g. 'en', 'pt'.", max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('project', 'slug', 'locale')},
        ),
    ]
