# Generated by Django 5.2.8 on 2025-11-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_alter_page_unique_together_page_locale_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationitem',
            options={'ordering': ['location', 'locale', 'column', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', help_text='Language/locale for this navigation item', max_length=5),
        ),
    ]
