# Generated by Django 5.2.8 on 2025-11-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_add_navigation_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='header_background_mode',
            field=models.CharField(choices=[('none', 'None'), ('particles', 'Particles'), ('meteors', 'Meteors'), ('shooting-stars', 'Shooting stars'), ('aurora', 'Aurora'), ('vortex', 'Vortex')], default='particles', help_text='Header background effect for this project (particles, meteors, shooting stars, etc.)', max_length=50),
        ),
    ]
