# Generated by Django 5.2.8 on 2025-11-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_siteproject_header_background_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('eyebrow', models.CharField(blank=True, help_text='Small text above the main title.', max_length=120)),
                ('title', models.CharField(help_text='Main hero title for this slide.', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short subtitle or supporting line.', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Optional longer text under the subtitle.')),
                ('primary_button_label', models.CharField(blank=True, max_length=120)),
                ('primary_button_url', models.CharField(blank=True, max_length=255)),
                ('secondary_button_label', models.CharField(blank=True, max_length=120)),
                ('secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, help_text='Hero image URL for this slide (right side / background).')),
                ('animation_mode', models.CharField(choices=[('none', 'None'), ('fade-up', 'Fade up'), ('slide-left', 'Slide left'), ('typewriter', 'Typewriter')], default='fade-up', help_text="How this slide's text should animate.", max_length=32)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='sites.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
