# Generated by Django 5.2.8 on 2025-11-11 09:40

from django.db import migrations


def seed_home_hero_slides(apps, schema_editor):
    Page = apps.get_model("sites", "Page")
    HeroSlide = apps.get_model("sites", "HeroSlide")

    home_page = (
        Page.objects.filter(slug="home", locale="en").order_by("id").first()
    )
    if not home_page:
        return

    if HeroSlide.objects.filter(page=home_page).exists():
        return

    slides = [
        {
            "order": 0,
            "is_active": True,
            "eyebrow": "Just Code Works",
            "title": "Launch a website and prints without touching code.",
            "subtitle": "From idea to online in a few clicks.",
            "body": "Pick a template, answer a few simple questions, and we'll generate a live website plus ready-to-print business cards for your business.",
            "primary_button_label": "Start my website",
            "primary_button_url": "/signup",
            "secondary_button_label": "See how it works",
            "secondary_button_url": "/how-it-works",
            "image_url": "https://placehold.co/640x480?text=Hero+Slide+1",
            "animation_mode": "fade-up",
        },
        {
            "order": 1,
            "is_active": True,
            "eyebrow": "Websites + Printing",
            "title": "One place for your site, cards, and flyers.",
            "subtitle": "No more juggling tools and suppliers.",
            "body": "Design, content, and printing are all connected. Update your details once and your website and print materials stay in sync.",
            "primary_button_label": "View templates",
            "primary_button_url": "/websites",
            "secondary_button_label": "Printing options",
            "secondary_button_url": "/print",
            "image_url": "https://placehold.co/640x480?text=Hero+Slide+2",
            "animation_mode": "slide-left",
        },
        {
            "order": 2,
            "is_active": True,
            "eyebrow": "Built for non-tech people",
            "title": "If grandma can click, she can launch a website.",
            "subtitle": "We guide each step so nothing feels scary.",
            "body": "We ask plain questions, not technical ones. You focus on your business; we handle domains, hosting, and layouts behind the scenes.",
            "primary_button_label": "Try the builder",
            "primary_button_url": "/signup",
            "secondary_button_label": "",
            "secondary_button_url": "",
            "image_url": "https://placehold.co/640x480?text=Hero+Slide+3",
            "animation_mode": "typewriter",
        },
    ]

    for data in slides:
        HeroSlide.objects.create(page=home_page, **data)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_heroslide'),
    ]

    operations = [
        migrations.RunPython(seed_home_hero_slides, migrations.RunPython.noop),
    ]
