# Generated by Django 5.2.8 on 2025-11-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_auto_20251111_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproject',
            name='header_background_mode',
            field=models.CharField(choices=[('none', 'None'), ('particles', 'Particles')], default='particles', help_text='Header background effect for this project (particles, meteors, shooting stars, etc.)', max_length=50),
        ),
    ]
