# Generated by Django 5.2.8 on 2025-11-11 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_alter_siteproject_header_background_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text="Internal key used by the frontend to choose the layout (e.g. 'jcw-main').", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Human-readable template name (e.g. 'JCW Main Long Page').", max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='siteproject',
            name='site_template',
            field=models.ForeignKey(blank=True, help_text='Which site template/layout this project uses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='sites.sitetemplate'),
        ),
    ]
