# Generated by Django 5.2.8 on 2025-11-11 13:11

from django.db import migrations


def seed_site_templates(apps, schema_editor):
    SiteTemplate = apps.get_model("sites", "SiteTemplate")
    SiteProject = apps.get_model("sites", "SiteProject")

    jcw_main, _ = SiteTemplate.objects.get_or_create(
        key="jcw-main",
        defaults={
            "name": "JCW Main Long Page",
            "description": "Primary JCW long homepage layout with hero slider.",
            "is_active": True,
        },
    )

    SiteProject.objects.filter(site_template__isnull=True).update(site_template=jcw_main)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_sitetemplate_siteproject_site_template'),
    ]

    operations = [
        migrations.RunPython(seed_site_templates, migrations.RunPython.noop),
    ]
