# Generated by Django 5.2.8 on 2025-11-11 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_auto_20251111_1411'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The user who owns this project.', on_delete=django.db.models.deletion.CASCADE, related_name='site_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
