# Generated by Django 5.2.8 on 2025-11-11 16:14

from django.db import migrations


def seed_default_dashboard_template(apps, schema_editor):
    DashboardTemplate = apps.get_model("sites", "DashboardTemplate")
    DashboardBlock = apps.get_model("sites", "DashboardBlock")

    template, _ = DashboardTemplate.objects.get_or_create(
        key="default-tenant-dashboard",
        defaults={
            "name": "Default tenant dashboard",
            "description": "Standard overview shown to all tenants.",
            "is_active": True,
            "is_default_for_tenants": True,
        },
    )

    if not template.blocks.exists():
        blocks = [
            {
                "key": "live-preview",
                "title": "Live preview",
                "description": "Preview of your website once the builder is connected.",
                "region": "main",
                "order": 0,
                "is_active": True,
                "target_route": "/dashboard/website",
            },
            {
                "key": "next-steps",
                "title": "Next steps",
                "description": "Guidance on what to do after creating your project.",
                "region": "main",
                "order": 1,
                "is_active": True,
                "target_route": "/dashboard/website",
            },
            {
                "key": "quick-links",
                "title": "Quick links",
                "description": "Shortcuts to website, printing, and settings.",
                "region": "sidebar",
                "order": 0,
                "is_active": True,
                "target_route": "/dashboard",
            },
        ]
        for data in blocks:
            DashboardBlock.objects.create(template=template, **data)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_dashboardtemplate_dashboardblock'),
    ]

    operations = [
        migrations.RunPython(seed_default_dashboard_template, migrations.RunPython.noop),
    ]
