# Generated by Django 5.2.8 on 2025-11-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_auto_20251111_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplate',
            name='category',
            field=models.CharField(blank=True, help_text="Category or niche, e.g. 'Restaurant', 'Services', 'Ecommerce'.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='is_default_for_tenants',
            field=models.BooleanField(default=False, help_text='If true, this template is used as the default for tenant dashboards or sites.'),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='sections_count',
            field=models.PositiveIntegerField(default=0, help_text='How many sections/blocks this template includes.'),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publishing status for this template.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('email', 'Email'), ('landing', 'Landing page')], default='website', help_text='Kind of template (website, email, landing).', max_length=20),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this template has been used by tenants.'),
        ),
    ]
