# Generated by Django 5.2.8 on 2025-11-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_sitetemplate_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='is_master_template',
            field=models.BooleanField(default=False, help_text='If true, this project serves as a master template for cloning.'),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview image for this template.', null=True, upload_to='template_previews/'),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='version',
            field=models.CharField(blank=True, default='v1', help_text='Template version for tracking changes.', max_length=20),
        ),
    ]
