# Generated by Django 5.2.8 on 2025-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_alter_field_options_field_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplate',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='URL for the favicon image.'),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='footer_logo_url',
            field=models.URLField(blank=True, help_text='URL for the footer logo image.'),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='header_logo_url',
            field=models.URLField(blank=True, help_text='URL for the header logo image.'),
        ),
    ]
