# Generated by Django 5.2.8 on 2025-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0018_add_template_branding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplate',
            name='is_user_selectable',
            field=models.BooleanField(default=True, help_text='If False, this template is reserved for internal use and hidden from user-facing template pickers.'),
        ),
    ]
