# Generated by Django 5.2.8 on 2025-11-14 05:28

from django.db import migrations


def mark_jcw_main_as_internal(apps, schema_editor):
    """[TEMPLAB] mark jcw-main as internal"""
    SiteTemplate = apps.get_model('sites', 'SiteTemplate')
    
    try:
        jcw_template = SiteTemplate.objects.get(key='jcw-main')
        jcw_template.is_user_selectable = False
        jcw_template.save()
        print(f"Marked SiteTemplate '{jcw_template.name}' (key=jcw-main) as internal (is_user_selectable=False)")
    except SiteTemplate.DoesNotExist:
        print("No SiteTemplate with key='jcw-main' found - migration is a no-op")


def reverse_mark_jcw_main_as_internal(apps, schema_editor):
    """Reverse operation - mark jcw-main as user-selectable again"""
    SiteTemplate = apps.get_model('sites', 'SiteTemplate')
    
    try:
        jcw_template = SiteTemplate.objects.get(key='jcw-main')
        jcw_template.is_user_selectable = True
        jcw_template.save()
        print(f"Restored SiteTemplate '{jcw_template.name}' (key=jcw-main) as user-selectable")
    except SiteTemplate.DoesNotExist:
        print("No SiteTemplate with key='jcw-main' found - reverse migration is a no-op")


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0019_sitetemplate_is_user_selectable'),
    ]

    operations = [
        migrations.RunPython(
            mark_jcw_main_as_internal,
            reverse_mark_jcw_main_as_internal,
        ),
    ]
