# Generated by Django 5.2.8 on 2025-11-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_auto_20251114_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='indexable',
            field=models.BooleanField(default=True, help_text='If false, this page should be marked as noindex for search engines.'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO description shown in search results.'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_slug',
            field=models.SlugField(blank=True, help_text='Optional URL slug override for this locale. Defaults to slug/path.', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title. Defaults to page title if empty.', max_length=255),
        ),
    ]
