# Generated by Django 5.2.8 on 2025-11-15 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0021_page_indexable_page_meta_description_page_meta_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(help_text="Short machine-readable key like 'hero-banner', 'about-us', 'menu-list'", max_length=100)),
                ('internal_name', models.CharField(help_text="Human-readable label like 'Hero – Full-width image + CTA'", max_length=200)),
                ('code', models.SlugField(help_text="Complete section code following naming scheme: e.g. 'jcw-restaurant-modern-01-hero-01'", max_length=150)),
                ('group', models.CharField(blank=True, help_text="Section group like 'hero', 'about', 'menu', 'contact'", max_length=50, null=True)),
                ('variant_index', models.PositiveIntegerField(default=1, help_text='Which variation this is within the group (1, 2, 3, etc.)')),
                ('default_order', models.PositiveIntegerField(default=0, help_text='Default position/order suggestion on a page')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is available for use')),
                ('notes', models.TextField(blank=True, help_text='Internal notes, usage hints, etc.')),
                ('preview_image', models.URLField(blank=True, help_text='Optional image path for preview thumbnails')),
                ('site_template', models.ForeignKey(help_text='The site template this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sites.sitetemplate')),
            ],
            options={
                'ordering': ['site_template', 'group', 'default_order', 'id'],
                'unique_together': {('site_template', 'code')},
            },
        ),
    ]
