# Generated by Django 5.2.8 on 2025-11-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0022_templatesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesection',
            name='is_interactive',
            field=models.BooleanField(default=False, help_text='Whether this section requires user interaction (forms, galleries, sliders, etc.)'),
        ),
        migrations.AddField(
            model_name='templatesection',
            name='min_plan',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('premium', 'Premium')], default='free', help_text='Minimum subscription plan required to use this section', max_length=20),
        ),
        migrations.AddField(
            model_name='templatesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('menu', 'Menu'), ('pricing', 'Pricing'), ('testimonials', 'Testimonials'), ('gallery', 'Gallery'), ('faq', 'FAQ'), ('cta', 'Call to Action'), ('form-contact', 'Contact Form'), ('form-booking', 'Booking Form'), ('form-lead', 'Lead Generation Form'), ('form-quote', 'Quote Request Form'), ('features', 'Features'), ('services', 'Services'), ('team', 'Team'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('footer', 'Footer'), ('other', 'Other')], default='other', help_text='Type of section content (hero, about, menu, form, etc.)', max_length=50),
        ),
    ]
