# Generated by Django 5.2.8 on 2025-11-15 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0023_templatesection_is_interactive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Customer name', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Customer email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Customer phone number', max_length=50)),
                ('license_plate', models.CharField(blank=True, help_text='Vehicle license plate', max_length=20)),
                ('car_make_model', models.CharField(blank=True, help_text='Vehicle make and model', max_length=200)),
                ('service_type', models.CharField(blank=True, choices=[('troca_oleo', 'Troca de óleo'), ('revisao', 'Revisão geral'), ('travoes', 'Travões'), ('diagnostico', 'Diagnóstico'), ('outro', 'Outro')], help_text='Type of automotive service requested', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Additional message or problem description')),
                ('source_page_slug', models.CharField(blank=True, help_text="Page slug where form was submitted (e.g. 'orcamento')", max_length=100)),
                ('locale', models.CharField(default='pt', help_text='Form submission locale', max_length=10)),
                ('consent_marketing', models.BooleanField(default=False, help_text='Customer consent for marketing communications')),
                ('site_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='sites.siteproject')),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
