# Generated by Django 5.2.8 on 2025-11-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0024_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplate',
            name='preview_image_url',
            field=models.URLField(blank=True, help_text='External URL for template preview image (for auto-scroll demo).'),
        ),
    ]
