# Generated by Django 5.2.8 on 2025-11-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0025_sitetemplate_preview_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesection',
            name='source_section',
            field=models.ForeignKey(blank=True, help_text='Original section this template section was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_variants', to='sites.section'),
        ),
        migrations.CreateModel(
            name='TemplateSectionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="Field key used in the frontend config, e.g. 'title', 'subtitle'.", max_length=80)),
                ('label', models.CharField(blank=True, help_text='Human label shown in the editor UI.', max_length=120)),
                ('value', models.TextField(blank=True, help_text='Default/example value for this field')),
                ('order', models.PositiveIntegerField(default=0)),
                ('template_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sites.templatesection')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('template_section', 'key')},
            },
        ),
    ]
