# Generated by Django 5.2.8 on 2025-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0026_templatesection_source_section_templatesectionfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='background_color',
            field=models.CharField(default='#0B1120', help_text='Default background color in hex', max_length=7),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='is_dark_theme',
            field=models.BooleanField(default=True, help_text='If true, template can assume dark background by default'),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='secondary_color',
            field=models.CharField(default='#6366F1', help_text='Secondary accent color in hex', max_length=7),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='text_color',
            field=models.CharField(default='#F9FAFB', help_text='Default body text color in hex', max_length=7),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='accent_color',
            field=models.CharField(default='#F97316', help_text='Accent / CTA color in hex', max_length=7),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='primary_color',
            field=models.CharField(default='#1D4ED8', help_text='Primary brand/action color in hex, e.g. #1D4ED8', max_length=7),
        ),
    ]
