# Generated by Django 5.2.8 on 2025-11-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0027_siteproject_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='brand_primary_color',
            field=models.CharField(blank=True, help_text='User-preferred brand primary color in hex format.', max_length=7),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='brand_secondary_color',
            field=models.CharField(blank=True, help_text='User-preferred brand secondary color in hex format.', max_length=7),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='business_name',
            field=models.CharField(blank=True, help_text='Official business name for branding and legal purposes.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='entry_intent',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('prints', 'Prints'), ('pos', 'Point of Sale')], help_text='The primary intent when user entered onboarding (website, prints, pos).', max_length=20),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='onboarding_notes',
            field=models.TextField(blank=True, help_text='Internal notes from onboarding process.'),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='preferred_theme_mode',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (system preference)')], help_text='User preference for light/dark theme mode.', max_length=10),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='primary_country',
            field=models.CharField(blank=True, help_text='Primary country of business operation.', max_length=100),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='primary_language',
            field=models.CharField(blank=True, help_text='Primary language for content (ISO language code).', max_length=20),
        ),
    ]
