# Generated by Django 5.2.8 on 2025-11-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0028_add_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='entry_product',
            field=models.CharField(choices=[('website', 'Website'), ('printing', 'Printing'), ('pos', 'POS')], default='website', help_text='The product/service selected during Step 0 onboarding.', max_length=20),
        ),
    ]
