# Generated by Django 5.2.8 on 2025-11-17 16:04

import django.db.models.deletion
import sites.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0029_add_entry_product_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(help_text='Screenshot image (PNG/JPG/SVG) to generate section from.', upload_to=sites.models.section_draft_upload_to)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', help_text='Processing status of the section draft.', max_length=20)),
                ('section_name', models.CharField(blank=True, help_text='Optional name for the section being generated.', max_length=120)),
                ('ai_output_json', models.JSONField(blank=True, help_text='AI-generated section data (HTML, fields, etc.).', null=True)),
                ('locale', models.CharField(blank=True, help_text='Locale for generated content (en, pt, etc.).', max_length=10)),
                ('project', models.ForeignKey(help_text='Project this section draft belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='section_drafts', to='sites.siteproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
