# Generated by Django 5.2.8 on 2025-11-17 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0030_sectiondraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Slider name for admin reference', max_length=200)),
                ('slug', models.SlugField(help_text='Unique identifier for the slider', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_play', models.BooleanField(default=True, help_text='Auto-advance slides')),
                ('auto_play_interval', models.PositiveIntegerField(default=5000, help_text='Interval in milliseconds')),
                ('show_navigation', models.BooleanField(default=True, help_text='Show navigation arrows')),
                ('show_pagination', models.BooleanField(default=True, help_text='Show pagination dots')),
                ('particles_enabled', models.BooleanField(default=True, help_text='Enable particle effects')),
                ('particles_density', models.PositiveIntegerField(default=100, help_text='Number of particles (50-300)')),
                ('particles_speed', models.FloatField(default=1.0, help_text='Particle movement speed (0.5-3.0)')),
                ('particles_size_min', models.PositiveIntegerField(default=1, help_text='Minimum particle size')),
                ('particles_size_max', models.PositiveIntegerField(default=3, help_text='Maximum particle size')),
                ('particles_color', models.CharField(default='#ffffff', help_text='Particle color (hex)', max_length=7)),
                ('particles_opacity', models.FloatField(default=0.6, help_text='Particle opacity (0.1-1.0)')),
                ('background_type', models.CharField(choices=[('gradient', 'Gradient'), ('image', 'Background Image'), ('video', 'Background Video')], default='gradient', max_length=20)),
                ('gradient_from', models.CharField(default='#1e40af', help_text='Gradient start color (hex)', max_length=7)),
                ('gradient_to', models.CharField(default='#3b82f6', help_text='Gradient end color (hex)', max_length=7)),
                ('gradient_direction', models.CharField(choices=[('to-r', 'To Right'), ('to-l', 'To Left'), ('to-b', 'To Bottom'), ('to-t', 'To Top'), ('to-br', 'To Bottom Right'), ('to-bl', 'To Bottom Left'), ('to-tr', 'To Top Right'), ('to-tl', 'To Top Left')], default='to-br', max_length=10)),
                ('background_image', models.URLField(blank=True, null=True)),
                ('background_video', models.URLField(blank=True, null=True)),
                ('background_overlay_opacity', models.FloatField(default=0.3, help_text='Overlay opacity over image/video')),
                ('site_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_sliders', to='sites.siteproject')),
            ],
            options={
                'verbose_name': 'Homepage Slider',
                'verbose_name_plural': 'Homepage Sliders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, help_text='Main slide content/description', null=True)),
                ('primary_cta_text', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_cta_url', models.CharField(blank=True, max_length=500, null=True)),
                ('secondary_cta_text', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_cta_url', models.CharField(blank=True, max_length=500, null=True)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color (hex)', max_length=7)),
                ('text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('slide_image', models.URLField(blank=True, null=True)),
                ('slide_video', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('animation_type', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('none', 'No Animation')], default='fade', max_length=20)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='sites.homepageslider')),
            ],
            options={
                'verbose_name': 'Homepage Slide',
                'verbose_name_plural': 'Homepage Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_play', models.BooleanField(default=True)),
                ('auto_play_interval', models.PositiveIntegerField(default=4000)),
                ('slides_per_view', models.PositiveIntegerField(default=3, help_text='Number of testimonials visible at once')),
                ('site_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_carousels', to='sites.siteproject')),
            ],
            options={
                'verbose_name': 'Testimonial Carousel',
                'verbose_name_plural': 'Testimonial Carousels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_title', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_company', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_image', models.URLField(blank=True, null=True)),
                ('testimonial_text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='sites.testimonialcarousel')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
