# Generated by Django 5.2.8 on 2025-11-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0031_homepageslider_homepageslide_testimonialcarousel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslider',
            name='particles_colors',
            field=models.TextField(blank=True, help_text='JSON array of additional particle colors'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='particles_multi_color',
            field=models.BooleanField(default=False, help_text='Use multiple particle colors'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='particles_color',
            field=models.CharField(default='#ffffff', help_text='Primary particle color (hex)', max_length=7),
        ),
    ]
