# Generated by Django 5.2.8 on 2025-11-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0032_add_multi_color_particles'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='is_headquarters',
            field=models.BooleanField(default=False, help_text='Marks this project as the main Just Code Works website (HQ).'),
        ),
    ]
