# Generated by Django 5.2.8 on 2025-11-18 09:34

from django.db import migrations


def mark_hq_site(apps, schema_editor):
    """Mark SiteProjects that use the JCW Main template as headquarters."""
    SiteProject = apps.get_model("sites", "SiteProject")
    SiteTemplate = apps.get_model("sites", "SiteTemplate")

    try:
        # Find the HQ template by name or key
        hq_template = SiteTemplate.objects.get(name="JCW Main Long Page")
        print(f"Found HQ template: {hq_template.name} (key: {hq_template.key})")
        
        # Mark all projects using this template as HQ
        updated_count = SiteProject.objects.filter(site_template=hq_template).update(is_headquarters=True)
        print(f"Marked {updated_count} project(s) as headquarters.")
        
    except SiteTemplate.DoesNotExist:
        # Try finding by key as fallback
        try:
            hq_template = SiteTemplate.objects.get(key="jcw-main")
            print(f"Found HQ template by key: {hq_template.name}")
            updated_count = SiteProject.objects.filter(site_template=hq_template).update(is_headquarters=True)
            print(f"Marked {updated_count} project(s) as headquarters.")
        except SiteTemplate.DoesNotExist:
            print("Warning: No JCW Main template found. Skipping HQ marking.")


def reverse_mark_hq_site(apps, schema_editor):
    """Reverse the HQ marking."""
    SiteProject = apps.get_model("sites", "SiteProject")
    SiteProject.objects.filter(is_headquarters=True).update(is_headquarters=False)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0033_siteproject_is_headquarters'),
    ]

    operations = [
        migrations.RunPython(mark_hq_site, reverse_mark_hq_site),
    ]
