# Generated by Django 5.2.8 on 2025-11-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0034_mark_hq_site_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardBlock',
        ),
        migrations.DeleteModel(
            name='DashboardTemplate',
        ),
    ]
