# Generated by Django 5.2.8 on 2025-11-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0035_remove_dashboard_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='enable_arabic_language',
            field=models.BooleanField(default=False, help_text='Enable Arabic language for this website. When enabled, Arabic will be available in the language selector.'),
        ),
    ]
