# Generated by Django 5.2.8 on 2025-11-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0036_siteproject_enable_arabic_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWebsiteSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Slider name for admin reference', max_length=200)),
                ('slug', models.SlugField(help_text='Unique identifier for the slider', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_play', models.BooleanField(default=True, help_text='Auto-advance slides')),
                ('auto_play_interval', models.PositiveIntegerField(default=5000, help_text='Interval in milliseconds')),
                ('show_navigation', models.BooleanField(default=True, help_text='Show navigation arrows')),
                ('show_pagination', models.BooleanField(default=True, help_text='Show pagination dots')),
                ('particles_enabled', models.BooleanField(default=True, help_text='Enable particle effects')),
                ('particles_density', models.PositiveIntegerField(default=100, help_text='Number of particles (50-300)')),
                ('particles_speed', models.FloatField(default=1.0, help_text='Particle movement speed (0.5-3.0)')),
                ('particles_size_min', models.PositiveIntegerField(default=1, help_text='Minimum particle size')),
                ('particles_size_max', models.PositiveIntegerField(default=3, help_text='Maximum particle size')),
                ('particles_color', models.CharField(default='#ffffff', help_text='Primary particle color (hex)', max_length=7)),
                ('particles_colors', models.TextField(blank=True, help_text='JSON array of additional particle colors')),
                ('particles_opacity', models.FloatField(default=0.6, help_text='Particle opacity (0.1-1.0)')),
                ('particles_multi_color', models.BooleanField(default=False, help_text='Use multiple particle colors')),
                ('background_type', models.CharField(choices=[('gradient', 'Gradient'), ('image', 'Background Image'), ('video', 'Background Video')], default='gradient', max_length=20)),
                ('gradient_from', models.CharField(default='#1e40af', help_text='Gradient start color (hex)', max_length=7)),
                ('gradient_to', models.CharField(default='#3b82f6', help_text='Gradient end color (hex)', max_length=7)),
                ('gradient_direction', models.CharField(choices=[('to-r', 'To Right'), ('to-l', 'To Left'), ('to-b', 'To Bottom'), ('to-t', 'To Top'), ('to-br', 'To Bottom Right'), ('to-bl', 'To Bottom Left'), ('to-tr', 'To Top Right'), ('to-tl', 'To Top Left')], default='to-br', max_length=10)),
                ('background_image', models.URLField(blank=True, null=True)),
                ('background_video', models.URLField(blank=True, null=True)),
                ('background_overlay_opacity', models.FloatField(default=0.3, help_text='Overlay opacity over image/video')),
            ],
            options={
                'verbose_name': 'Main Website Slider',
                'verbose_name_plural': 'Main Website Sliders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainWebsiteSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, help_text='Main slide content/description', null=True)),
                ('primary_cta_text', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_cta_url', models.CharField(blank=True, max_length=500, null=True)),
                ('secondary_cta_text', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_cta_url', models.CharField(blank=True, max_length=500, null=True)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color (hex)', max_length=7)),
                ('text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('slide_image', models.URLField(blank=True, null=True)),
                ('slide_video', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('animation_type', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('none', 'No Animation')], default='fade', max_length=20)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='sites.mainwebsiteslider')),
            ],
            options={
                'verbose_name': 'Main Website Slide',
                'verbose_name_plural': 'Main Website Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
