# Generated by Django 5.2.8 on 2025-11-19 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0037_mainwebsiteslider_mainwebsiteslide'),
    ]

    operations = [
        # Drop old slider tables that are no longer needed
        migrations.RunSQL("DROP TABLE IF EXISTS sites_mainwebsiteslider;"),
        migrations.RunSQL("DROP TABLE IF EXISTS sites_mainwebsiteslide;"),
        migrations.RunSQL("DROP TABLE IF EXISTS sites_heroslide;"),
        migrations.RunSQL("DROP TABLE IF EXISTS sites_testimonialslide;"),
        # Keep sites_homepageslider and sites_homepageslide as they're still used for tenant websites
    ]
