# Generated by Django 5.2.8 on 2025-11-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0038_remove_old_slider_tables'),
    ]

    operations = [
    ]
